// autogenerated: do not add any changes
#include "heightmap_configuration.h"
namespace gb
{
std::string heightmap_configuration::get_heightmap_data_filename(void) const
{
const auto& iterator = m_attributes.find("/heightmap/heightmap_data_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void heightmap_configuration::set_heightmap_data_filename(std::string heightmap_data_filename)
{
configuration::set_attribute("/heightmap/heightmap_data_filename", std::make_shared<configuration_attribute>(heightmap_data_filename));
}
#endif
std::string heightmap_configuration::get_splatting_material_filename(void) const
{
const auto& iterator = m_attributes.find("/heightmap/splatting_material_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void heightmap_configuration::set_splatting_material_filename(std::string splatting_material_filename)
{
configuration::set_attribute("/heightmap/splatting_material_filename", std::make_shared<configuration_attribute>(splatting_material_filename));
}
#endif
std::vector<std::shared_ptr<configuration>> heightmap_configuration::get_materials_configurations(void) const
{
const auto& iterator = m_configurations.find("/heightmap/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void heightmap_configuration::add_materials_configurations(const std::shared_ptr<gb::material_configuration>& material)
{
configuration::set_configuration("/heightmap/materials/material", material);
}
#endif
#if defined(__EDITOR__)
void heightmap_configuration::set_materials_configurations(const std::shared_ptr<gb::material_configuration>& material, i32 index)
{
configuration::set_configuration("/heightmap/materials/material", material, index);
}
#endif
void heightmap_configuration::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml_document(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/heightmap");
std::string heightmap_data_filename = node.node().attribute("heightmap_data_filename").as_string();
configuration::set_attribute("/heightmap/heightmap_data_filename", std::make_shared<configuration_attribute>(heightmap_data_filename));
std::string splatting_material_filename = node.node().attribute("splatting_material_filename").as_string();
configuration::set_attribute("/heightmap/splatting_material_filename", std::make_shared<configuration_attribute>(splatting_material_filename));
pugi::xpath_node_set material_nodes = document.select_nodes("/heightmap/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
material->serialize((*iterator).node().attribute("filename").as_string());
configuration::set_configuration("/heightmap/materials/material", material);
}
}
#if defined(__EDITOR__)
void heightmap_configuration::deserialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = document.load("");
assert(result.status == pugi::status_ok);
pugi::xml_node node = document.append_child("heightmap");
pugi::xml_node parent_node = node;
pugi::xml_attribute attribute;
attribute = node.append_attribute("heightmap_data_filename");
std::string heightmap_data_filename = heightmap_configuration::get_heightmap_data_filename();
attribute.set_value(heightmap_data_filename.c_str());
attribute = node.append_attribute("splatting_material_filename");
std::string splatting_material_filename = heightmap_configuration::get_splatting_material_filename();
attribute.set_value(splatting_material_filename.c_str());
node = parent_node.append_child("materials");
for(const auto& iterator : heightmap_configuration::get_materials_configurations())
{
std::shared_ptr<gb::material_configuration> configuration = std::static_pointer_cast<gb::material_configuration>(iterator);
pugi::xml_node child_node = node.append_child("material");
attribute = child_node.append_attribute("filename");
attribute.set_value(configuration->get_filename().c_str());
}
document.save_file(filename.c_str());
}
#endif
}
